import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import dynamic from "next/dynamic";

const SidebarProvider = dynamic(
	() => import("@/state/functions/sidebar.state"),
	{ ssr: false },
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<ClerkProvider
			appearance={{
				baseTheme: dark,
			}}
		>
			<html lang='en'>
				<body className={inter.className}>
					<ThemeProvider
						attribute='class'
						forcedTheme='dark'
						storageKey='stream-hub-theme'
					>
						<SidebarProvider>{children}</SidebarProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
